name: Android CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Build release APK/AAB
      run: |
        ./gradlew assembleRelease || echo "Release build failed"
        ./gradlew bundleRelease || echo "Bundle build failed"

    - name: Find and list build outputs
      run: |
        echo "=== APK Files ==="
        find app/build/outputs/apk -name "*.apk" -exec ls -lh {} \;
        echo "=== AAB Files ==="
        find app/build/outputs/bundle -name "*.aab" -exec ls -lh {} \;
        echo "=== All Outputs ==="
        ls -R app/build/outputs || true

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: |
          app/build/outputs/apk/**/*release*.apk
          !app/build/outputs/apk/**/*unaligned*.apk
        if-no-files-found: warn

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: app/build/outputs/bundle/**/*release*.aab
        if-no-files-found: warn

    - name: Upload mapping file (for crash reporting)
      uses: actions/upload-artifact@v4
      with:
        name: mapping-file
        path: app/build/outputs/mapping/**/mapping.txt
        if-no-files-found: ignore
