name: Android CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # पूरा इतिहास fetch करेगा (Git submodules के लिए जरूरी)

    - name: Verify Gradle Wrapper
      run: |
        if [ ! -f "gradlew" ]; then
          echo "::warning::gradlew file missing, generating wrapper..."
          ./gradlew wrapper || gradle wrapper
        fi

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: |
        ./gradlew assembleDebug
        ./gradlew assembleRelease || echo "Release build failed - continuing"
        ./gradlew bundleRelease || echo "Bundle build failed - continuing"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-build-outputs
        path: |
          app/build/outputs/apk/**/*.apk
          app/build/outputs/bundle/**/*.aab
        if-no-files-found: warn
